### ISSUE TITLE
Prompt template is not translated to Chinese

### ISSUE THREAD

**Issue by ngoanpv** [ymcui/Chinese-LLaMA-Alpaca#446]
Please let me know why the Prompt template at the fine tuning code which not translated to Chinese ?
`PROMPT_TEMPLATE = (
        "Below is an instruction that describes a task. "
        "Write a response that appropriately completes the request.\n\n"
        "### Instruction:\n{instruction}\n\n### Response: "
    )`

**Comment by ymcui** [comment]
Because our released Alpaca models are trained in that way.
The main purpose is to inherit English ability of the original LLaMA when adapting to Chinese data.
As we have not thoroughly tested whether it is better to use English or Chinese prompt template, you are free to use another desired template if you would like to train your own model.

**Comment by ngoanpv** [comment]
I comprehend the essence of alpaca instruction fine-tuning derived from the original LLaMA. Nonetheless, I believe it would be more logical to adapt the prompt for a specific language, such as Chinese. By the way, I appreciate your repository and your valuable contributions.
