### ISSUE TITLE
AttributeError: 'LlamaTokenizerFast' object has no attribute 'sp_model'

### ISSUE THREAD

**Issue by Kowsher** [ymcui/Chinese-LLaMA-Alpaca#866]
### Check before submitting issues

- [X] Make sure to pull the latest code, as some issues and bugs have been fixed.
- [X] Due to frequent dependency updates, please ensure you have followed the steps in our [Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)
- [X] I have read the [FAQ section](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/FAQ) AND searched for similar issues and did not find a similar problem or solution
- [X] Third-party plugin issues - e.g., [llama.cpp](https://github.com/ggerganov/llama.cpp), [text-generation-webui](https://github.com/oobabooga/text-generation-webui), [LlamaChat](https://github.com/alexrozanski/LlamaChat), we recommend checking the corresponding project for solutions
- [X] Model validity check - Be sure to check the model's [SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md). If the model is incorrect, we cannot guarantee its performance

### Type of Issue

Model conversion and merging

### Base Model

LLaMA-7B

### Operating System

Linux

### Describe your issue in detail

```
# Please copy-and-paste your command here.
```
When I'm going to Marge tokenizer, I get this error
'AttributeError: 'LlamaTokenizerFast' object has no attribute 'sp_model''

llama_spm = sp_pb2_model.ModelProto()
llama_spm.ParseFromString(llama_tokenizer.sp_model.serialized_model_proto())

### Dependencies (must be provided for code-related issues)

```
# Please copy-and-paste your dependencies here.
```

### Execution logs or screenshots

```
# Please copy-and-paste your logs here.
```

**Comment by ymcui** [comment]
Did you use the recommended version of `transformers`? See [`requirements.txt`](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/requirements.txt)

**Comment by Kowsher** [comment]
> Did you use the recommended version of `transformers`? See [`requirements.txt`](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/requirements.txt)

Yes, i followed it, but it works on tokenizer, facing issue in fastokenizer.

**Comment by ymcui** [comment]
Unfortunately, our script is only tested under non-fast tokenizer merging.

**Comment by CaoHanyun** [comment]
That's true. I also ran into the same problem. And I think that's because LlamaTokenizerFast is not the same as LlamaTokenizer. The former is just a bpe-tokenizer(btw it is easy to load with a tokenizer.json trained by the library of huggingface/tokenizers), while the latter is equipped more with sp_model. It can be seen that LlamaTokenizerFast 
 has no object named 'sp_model' till now.(https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/tokenization_llama_fast.py)
 - The image attached shows how LlamaTokenizer supports sp_model.
![微信图片_LlamaTokenizerFast](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/61311604/2e3468de-87a1-425e-b663-eb72e75fffd8)

**Comment by StephennFernandes** [comment]
facing similar issue tried the recommended version, but still issue persists whats the fix for this ?
