### ISSUE TITLE
how to start with adapter_model.bin in  Chinese-Alpaca-13B

### ISSUE THREAD

**Issue by ukhack** [ymcui/Chinese-LLaMA-Alpaca#98]
I can run gpt4all dirctly with gpt4all provide bin.
Can adapter_model.bin provided by Chinese-Alpaca-13B run dirctly？
Do I need to download this repository and llama.cpp-master, remake and quantify, or what should I do?

**Comment by airaria** [comment]
You may need to follow steps in the README to merge the lora and the llama with the provided script since the release Chinese-llama has a different vocab size.

Or, specifically, you resize the original llama weight to the new vocabulary size (49954 for alpaca model), then you should able to run Chinese-Alpaca with adapter_model.bin provided (also remember to use  the Chinese-alpaca tokenizer)

**Comment by ukhack** [comment]
Thank you very much. I followed your steps and ran the Chinese-Alpaca successfully.
Appreciate your Detailed help documentation!
